import { Product, Order, Review } from "./types";

export const PRODUCTS: Product[] = [
  // ── Beverages › Water & Soft Drinks ────────────────────────────────────────
  {
    id: 1,
    name: "Aquafina Purified Water 500ml",
    category: "beverages",
    subcategory: "water-soft-drinks",
    price: 8000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "💧",
    image: "/image/image1.png",
    desc: "Purified bottled drinking water.",
  },
  {
    id: 2,
    name: "LaVie Mineral Water 500ml",
    category: "beverages",
    subcategory: "water-soft-drinks",
    price: 10000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🫙",
    image: "/image/image2.png",
    desc: "Natural mineral water.",
  },
  {
    id: 3,
    name: "Coca-Cola Original 330ml",
    category: "beverages",
    subcategory: "water-soft-drinks",
    price: 12000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🧃",
    image: "/image/image3.jpg",
    desc: "Classic carbonated soft drink.",
  },
  {
    id: 4,
    name: "Sprite Lemon-Lime 330ml",
    category: "beverages",
    subcategory: "water-soft-drinks",
    price: 12000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🥤",
    image: "/image/image4.png",
    desc: "Refreshing lemon-lime soda.",
  },
  {
    id: 5,
    name: "Fanta Orange 330ml",
    category: "beverages",
    subcategory: "water-soft-drinks",
    price: 12000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🍋",
    image: "/image/image5.png",
    desc: "Orange flavored soft drink.",
  },

  // ── Beverages › Tea & Coffee ───────────────────────────────────────────────
  {
    id: 6,
    name: "C2 Green Tea 455ml",
    category: "beverages",
    subcategory: "tea-coffee",
    price: 10000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🍵",
    image: "/image/tea1.png",
    desc: "Ready-to-drink green tea.",
  },
  {
    id: 7,
    name: "Lipton Black Tea 350ml",
    category: "beverages",
    subcategory: "tea-coffee",
    price: 12000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🧋",
    image: "/image/tea2.png",
    desc: "Refreshing black tea drink.",
  },
  {
    id: 8,
    name: "Birdy Canned Coffee 240ml",
    category: "beverages",
    subcategory: "tea-coffee",
    price: 15000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "☕",
    image: "/image/tea3.png",
    desc: "Ready-to-drink canned coffee.",
  },

  // ── Snacks & Confectionery › Chips & Snacks ────────────────────────────────
  {
    id: 9,
    name: "Lay's Classic Potato Chips 52g",
    category: "snacks",
    subcategory: "chips-snacks",
    price: 15000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🥜",
    image: "/image/snack1.jpg",
    desc: "Crispy salted potato chips.",
  },
  {
    id: 10,
    name: "Oishi Prawn Crackers 60g",
    category: "snacks",
    subcategory: "chips-snacks",
    price: 12000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🥔",
    image: "/image/snack2.jpg",
    desc: "Crunchy prawn snack.",
  },
  {
    id: 11,
    name: "One One Rice Crackers 150g",
    category: "snacks",
    subcategory: "chips-snacks",
    price: 18000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🌿",
    image: "/image/snack3.jpg",
    desc: "Crispy rice crackers.",
  },
  {
    id: 12,
    name: "Tao Kae Noi Seaweed Snack 32g",
    category: "snacks",
    subcategory: "chips-snacks",
    price: 25000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🍤",
    image: "/image/snack4.jpg",
    desc: "Roasted seaweed snack.",
  },
  {
    id: 13,
    name: "NONGSHIM Shrimp Meat Flavored Chips 70g",
    category: "snacks",
    subcategory: "chips-snacks",
    price: 25000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🌾",
    image: "/image/snack5.jpg",
    desc: "Crispy shrimp-flavored potato snack with a light savory seafood taste and crunchy texture.",
  },

  // ── Snacks & Confectionery › Sweets ────────────────────────────────────────
  {
    id: 14,
    name: "Alpenliebe Original Caramel 119g",
    category: "snacks",
    subcategory: "sweets",
    price: 20000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🍫",
    image: "/image/sweet1.png",
    desc: "Creamy hard candy.",
  },
  {
    id: 15,
    name: "Hi-Chew Fruit Chews Grape Candy 50g",
    category: "snacks",
    subcategory: "sweets",
    price: 18000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🍬",
    image: "/image/sweet2.png",
    desc: "Soft chewy candy.",
  },
  {
    id: 16,
    name: "KitKat 4 Finger Bar",
    category: "snacks",
    subcategory: "sweets",
    price: 18000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🍿",
    image: "/image/sweet3.png",
    desc: "Chocolate wafer bar.",
  },
  {
    id: 17,
    name: "Oreo Original Cookies 133g",
    category: "snacks",
    subcategory: "sweets",
    price: 18000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🍪",
    image: "/image/sweet4.png",
    desc: "Chocolate sandwich cookies.",
  },
  {
    id: 18,
    name: "Loacker Vanilla Wafers 45g",
    category: "snacks",
    subcategory: "sweets",
    price: 15000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🧇",
    image: "/image/sweet5.png",
    desc: "Vanilla cream wafers.",
  },

  // ── Food › Instant Foods ────────────────────────────────────────────────────
  {
    id: 19,
    name: "Hảo Hảo Shrimp Noodles",
    category: "food",
    subcategory: "instant-foods",
    price: 5000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🍜",
    image: "/image/instant1.png",
    desc: "Instant shrimp noodles.",
  },
  {
    id: 20,
    name: "Omachi Beef Cup Noodles",
    category: "food",
    subcategory: "instant-foods",
    price: 18000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🥣",
    image: "/image/instant2.png",
    desc: "Premium beef cup noodles.",
  },
  {
    id: 21,
    name: "Vifon Chicken Porridge",
    category: "food",
    subcategory: "instant-foods",
    price: 12000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🧀",
    image: "/image/instant3.png",
    desc: "Instant chicken porridge.",
  },
  {
    id: 22,
    name: "Kokomi Sour & Spicy Noodles 90g",
    category: "food",
    subcategory: "instant-foods",
    price: 10000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🍲",
    image: "/image/instant4.png",
    desc: "Sour and spicy instant noodles.",
  },
  {
    id: 23,
    name: "Vifon Instant Pho Beef Flavor 70g",
    category: "food",
    subcategory: "instant-foods",
    price: 15000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🍝",
    image: "/image/instant5.png",
    desc: "Vietnamese beef pho noodles.",
  },

  // ── Food › Ready & Canned Foods ────────────────────────────────────────────
  {
    id: 24,
    name: "Spam Classic Luncheon Meat 340g",
    category: "food",
    subcategory: "ready-canned",
    price: 170000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🐟",
    image: "/image/ready1.png",
    desc: "Ready-to-eat canned luncheon meat.",
  },
  {
    id: 25,
    name: "Ayam Brand Tuna Chunks 185g",
    category: "food",
    subcategory: "ready-canned",
    price: 55000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🥫",
    image: "/image/ready2.png",
    desc: "Premium canned tuna chunks.",
  },
  {
    id: 26,
    name: "Vissan Canned Pork 150g",
    category: "food",
    subcategory: "ready-canned",
    price: 32000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🍅",
    image: "/image/ready3.png",
    desc: "Ready-to-eat canned pork.",
  },
  {
    id: 27,
    name: "H&H Mackerel in Tomato Sauce 155g",
    category: "food",
    subcategory: "ready-canned",
    price: 45000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🐠",
    image: "/image/ready4.png",
    desc: "Canned mackerel in rich tomato sauce, ready to eat and high in protein.",
  },

  // ── Personal Care › Oral & Hair Care ───────────────────────────────────────
  {
    id: 28,
    name: "Colgate Total Toothpaste 150g",
    category: "personal-care",
    subcategory: "oral-hair-care",
    price: 45000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🦷",
    image: "/image/oral1.png",
    desc: "Complete oral protection.",
  },
  {
    id: 29,
    name: "Oral-B Classic Toothbrush",
    category: "personal-care",
    subcategory: "oral-hair-care",
    price: 25000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🪥",
    image: "/image/oral2.png",
    desc: "Soft bristle toothbrush.",
  },
  {
    id: 30,
    name: "Listerine Cool Mint 250ml",
    category: "personal-care",
    subcategory: "oral-hair-care",
    price: 65000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🧴",
    image: "/image/oral3.png",
    desc: "Antibacterial mouthwash.",
  },
  {
    id: 31,
    name: "Pantene Shampoo 650ml",
    category: "personal-care",
    subcategory: "oral-hair-care",
    price: 120000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "💆",
    image: "/image/oral4.png",
    desc: "Smooth & silky shampoo.",
  },
  {
    id: 32,
    name: "Pantene Conditioner 650ml",
    category: "personal-care",
    subcategory: "oral-hair-care",
    price: 120000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "✂️",
    image: "/image/oral5.png",
    desc: "Nourishing conditioner.",
  },

  // ── Personal Care › Body & Skin Care ───────────────────────────────────────
  {
    id: 33,
    name: "Lifebuoy Body Wash 850g",
    category: "personal-care",
    subcategory: "body-skin-care",
    price: 115000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "✨",
    image: "/image/body1.png",
    desc: "Antibacterial body wash.",
  },
  {
    id: 34,
    name: "Dove Beauty Bar Soap 90g",
    category: "personal-care",
    subcategory: "body-skin-care",
    price: 18000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "💎",
    image: "/image/body2.png",
    desc: "Moisturizing soap.",
  },
  {
    id: 35,
    name: "Nivea Body Lotion 400ml",
    category: "personal-care",
    subcategory: "body-skin-care",
    price: 120000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "☀️",
    image: "/image/body3.png",
    desc: "Daily moisturizing lotion.",
  },
  {
    id: 36,
    name: "Cetaphil Gentle Cleanser 125ml",
    category: "personal-care",
    subcategory: "body-skin-care",
    price: 180000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🫧",
    image: "/image/body4.png",
    desc: "Gentle facial cleanser.",
  },
  {
    id: 37,
    name: "Sunplay Skin Aqua SPF50+",
    category: "personal-care",
    subcategory: "body-skin-care",
    price: 120000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🧼",
    image: "/image/body5.png",
    desc: "UV protection sunscreen.",
  },

  // ── Household Essentials › Laundry & Cleaning ──────────────────────────────
  {
    id: 38,
    name: "OMO Matic Detergent 3kg",
    category: "household",
    subcategory: "laundry-cleaning",
    price: 180000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🧺",
    image: "/image/cleaning1.png",
    desc: "Laundry detergent.",
  },
  {
    id: 39,
    name: "Comfort Softener 1.8L",
    category: "household",
    subcategory: "laundry-cleaning",
    price: 95000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🧹",
    image: "/image/cleaning2.png",
    desc: "Fabric softener.",
  },
  {
    id: 40,
    name: "Gift Multi-Purpose Cleaner 900ml",
    category: "household",
    subcategory: "laundry-cleaning",
    price: 45000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🌸",
    image: "/image/cleaning3.png",
    desc: "Multi-surface cleaner.",
  },
  {
    id: 41,
    name: "Sunlight Dishwashing Liquid 750ml",
    category: "household",
    subcategory: "laundry-cleaning",
    price: 42000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🫧",
    image: "/image/cleaning4.png",
    desc: "Dishwashing liquid.",
  },
  {
    id: 42,
    name: "Gift Floor Cleaner 1L",
    category: "household",
    subcategory: "laundry-cleaning",
    price: 55000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🪣",
    image: "/image/cleaning5.png",
    desc: "Floor cleaning solution.",
  },

  // ── Household Essentials › Paper & Storage ─────────────────────────────────
  {
    id: 43,
    name: "Pulppy Toilet Paper 10 Rolls",
    category: "household",
    subcategory: "paper-storage",
    price: 75000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🧻",
    image: "/image/paper1.png",
    desc: "Soft toilet tissue.",
  },
  {
    id: 44,
    name: "Bless You Tissue Box",
    category: "household",
    subcategory: "paper-storage",
    price: 25000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "📦",
    image: "/image/paper2.png",
    desc: "Facial tissue paper.",
  },
  {
    id: 45,
    name: "Bobby Wet Wipes 80 Sheets",
    category: "household",
    subcategory: "paper-storage",
    price: 35000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🗂️",
    image: "/image/paper3.png",
    desc: "Gentle wet wipes.",
  },
  {
    id: 46,
    name: "Reynolds Aluminum Foil 10m",
    category: "household",
    subcategory: "paper-storage",
    price: 45000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🗂️",
    image: "/image/paper4.png",
    desc: "Food-grade aluminum foil.",
  },
  {
    id: 47,
    name: "Ziploc Storage Bags 20pcs",
    category: "household",
    subcategory: "paper-storage",
    price: 55000,
    original: null,
    rating: 4.5,
    reviews: 100,
    emoji: "🔒",
    image: "/image/paper5.png",
    desc: "Resealable storage bags.",
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "#AM72841",
    date: "May 20, 2025",
    status: "delivered",
    payment: "VNPay",
    items: [
      { pid: 33, qty: 1 },
      { pid: 35, qty: 2 },
    ],
  },
  {
    id: "#AM61023",
    date: "May 14, 2025",
    status: "shipping",
    payment: "COD",
    items: [{ pid: 38, qty: 1 }],
  },
  {
    id: "#AM55890",
    date: "May 5, 2025",
    status: "processing",
    payment: "VNPay",
    items: [
      { pid: 6, qty: 3 },
      { pid: 14, qty: 2 },
      { pid: 9, qty: 1 },
    ],
  },
  {
    id: "#AM48234",
    date: "Apr 28, 2025",
    status: "delivered",
    payment: "COD",
    items: [
      { pid: 8, qty: 1 },
      { pid: 7, qty: 2 },
    ],
  },
  {
    id: "#AM43100",
    date: "Apr 15, 2025",
    status: "cancelled",
    payment: "VNPay",
    items: [{ pid: 34, qty: 1 }],
  },
  {
    id: "#AM39876",
    date: "Apr 2, 2025",
    status: "delivered",
    payment: "COD",
    items: [
      { pid: 1, qty: 1 },
      { pid: 36, qty: 1 },
    ],
  },
  {
    id: "#AM31456",
    date: "Mar 20, 2025",
    status: "delivered",
    payment: "VNPay",
    items: [
      { pid: 10, qty: 2 },
      { pid: 2, qty: 4 },
    ],
  },
];

export const MY_REVIEWS: Review[] = [
  {
    pid: 33,
    rating: 5,
    title: "Absolute game-changer for my skin!",
    body: "I've been using this serum for 2 months and the difference is incredible. Dark spots have visibly faded and my skin looks so much brighter.",
    pros: "Visible results, lightweight, absorbs fast",
    cons: "A bit pricey but worth it",
    date: "May 18, 2025",
    helpful: 24,
  },
  {
    pid: 35,
    rating: 5,
    title: "Best sunscreen I've ever tried",
    body: "No white cast, comfortable to wear all day. Reapplying is easy and it doesn't feel greasy at all. Would 100% recommend.",
    pros: "No white cast, reef-safe, water resistant",
    cons: "Wish it came in a larger size",
    date: "May 10, 2025",
    helpful: 18,
  },
  {
    pid: 7,
    rating: 5,
    title: "My morning coffee ritual changed",
    body: "Smooth, rich, and never bitter. The cold brew concentrate is super versatile — I use it hot or cold depending on my mood. Amazing product.",
    pros: "Smooth flavor, convenient, great value",
    cons: "Wish it had a decaf option",
    date: "Apr 30, 2025",
    helpful: 12,
  },
  {
    pid: 1,
    rating: 4,
    title: "Best sparkling water I've had",
    body: "Crisp and refreshing with just the right amount of carbonation. Not overly gassy and has a clean mineral taste. Great for daily hydration.",
    pros: "Great taste, no artificial flavors, well priced",
    cons: "Wish the case was bigger",
    date: "Apr 12, 2025",
    helpful: 7,
  },
  {
    pid: 10,
    rating: 5,
    title: "Absolutely addictive BBQ chips!",
    body: "The perfect balance of sweet and smoky BBQ flavor. The kettle-cooked texture gives a satisfying crunch regular chips can't match. Will buy again!",
    pros: "Incredible crunch, bold flavor, resealable bag",
    cons: "Hard to stop at just one serving",
    date: "Mar 28, 2025",
    helpful: 9,
  },
];

export const PENDING_PIDS = [8, 36, 2];
export const STAR_LABELS = ["", "Terrible", "Bad", "Okay", "Good", "Excellent"];
